name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          packager: yarn
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build and deploy
        run: eas build -p android --profile=production --auto-submit --non-interactive --no-wait
        working-directory: ./apps/app

  deploy-dashboard:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          packager: yarn
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build and deploy
        run: eas build -p android --profile=production --auto-submit --non-interactive --no-wait
        working-directory: ./apps/dashboard
