name: Deploy

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      app: ${{ steps.filter.outputs.app }}
      dashboard: ${{ steps.filter.outputs.dashboard }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app:
              - 'apps/app/**'
            dashboard:
              - 'apps/dashboard/**'

  deploy-app:
    needs: changes
    if: ${{ needs.changes.outputs.app == 'true' }}
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          packager: yarn
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build and deploy
        run: eas build -p android --profile=production --auto-submit --non-interactive --no-wait
        working-directory: ./apps/app

  deploy-dashboard:
    needs: changes
    if: ${{ needs.changes.outputs.dashboard == 'true' }}
    name: Deploy dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          packager: yarn
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build and deploy
        run: eas build -p android --profile=production --auto-submit --non-interactive --no-wait
        working-directory: ./apps/dashboard
